export const variants = [
    {
        mainColor:"#FDEDED",
        secondaryColor:"#F16360",
        symbol:"error",
        title:"Error"
    },
    {
        mainColor:"#FFF4E5",
        secondaryColor:"#FFA117",
        symbol:"warning",
        title:"Warning"
    },
    {
        mainColor:"#EDFEEE",
        secondaryColor:"#5CB660",
        symbol:"check_circle",
        title:"Success"
    }
]